#!/usr/bin/env python3
# This is a singe line commet
# Python programme to illustrate
# Name : brian kibet
# Email : blkagatum@gmail.com
# Date : 17th Feb 2023
# File : surface_area_sphere
pi = 3.142
r = input("enter the radius of the sphere")
surface_area_sphere =(4*pi*int(r)*int(r))
print(surface_area_sphere)