f_name = input("what is your name")

print("my name is", f_name)
s_name = input("what is your second name")
print("my second is ",s_name)
f_num =input("Enter first number:")
s_num =input("enter the second:")
#converting the string into intergers
sum_num = int(f_num) + int(s_num)
diff_num = int(f_num) - int(s_num)
quot_num = int(f_num) / int(s_num)
pro_num = int(f_num) * int(s_num)
print("the sum of the number is:",sum_num)
print("the difference of the number is:",diff_num)
print("the quotient of the number is:",quot_num)
print("the product of the number is:",pro_num)