#!/usr/bin/env python3
# This is a singe line commet
# Python programme to illustrate
# Name : brian kibet
# Email : blkagatum@gmail.com
# Date : 17th Feb 2023
# File : assignment2
# import module
from tabulate import tabulate
# assign data = 
    
    {['a','b','c']
    [1 , 2 , 3 ]
    ['brian','kibet','lagat',]}

