
function add_numbers(num1,num2)

{
    return num1 + num2
}add_numbers(34,56)
console.log("javascript conso")
document.getElementsById("confir_btn").onclick = function(){
    age = document.getElementById("age").innerHTML=value()
if(age<= 18){
    msg = "you are not allowed"
    document.getElementById("get_in").innerHTML=Msg

}else{
    msg = "welcome to the club"
    document.getElementById("get_in").innerHTML=Msg